apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: "88.200.23.239"
    k8sServicePort: 6443
    #cni:
    #  chainingMode: "none"
      # binPath
      # confPath
      # logFile (default: "/var/run/cilium/cilium-cni.log")
    debug:
      enabled: true
    operator:
      enabled: true
      replicas: 1
    ingressController:
      enabled: false
    gatewayAPI:
      enabled: false
    #externalIP:
    #  enabled: false
    enableRuntimeDeviceDetection: true # experimental feature
    devices: "lan+"
    l2announcements:
      enabled: false
      leaseDuration: "3s"
      leaseRenewDeadline: "1s"
      leaseRetryPeriod: "500ms"
    l7Proxy: false
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    # bgp
